services:
  db:
    image: postgres:16.1
    container_name: repeat-piter-catsgram
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=catsgram
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U dbuser -d catsgram" ]
      timeout: 5s
      interval: 5s
      retries: 10

  db-init:
    image: postgres:16.1
    container_name: repeat-piter-db-init
    depends_on:
      db:
        condition: service_healthy
    entrypoint:
      - bash
      - -c
      - |
        set -e
        psql postgresql://dbuser:12345@db:5432/catsgram -v ON_ERROR_STOP=1 <<-EOSQL
          DROP TABLE IF EXISTS posts;
          DROP TABLE IF EXISTS users;
        
          CREATE TABLE IF NOT EXISTS users (
            id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            username VARCHAR(40) NOT NULL,
            email VARCHAR(255) NOT NULL,
            password VARCHAR(40) NOT NULL,
            registration_date TIMESTAMP WITH TIME ZONE NOT NULL
          );
        
          CREATE TABLE IF NOT EXISTS posts (
            id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            author_id BIGINT NOT NULL REFERENCES users(id),
            description TEXT,
            post_date TIMESTAMP WITH TIME ZONE NOT NULL
          );
        EOSQL